services:
  ollama:
    volumes:
      - /app/ollama/data:/root/.ollama
    container_name: ollama
    pull_policy: always
    tty: true
    restart: unless-stopped
    image: ollama/ollama:latest
    ports:
      - 127.0.0.1:11434:11434
    environment:
      - OLLAMA_KEEP_ALIVE=1h
    networks:
      - ollama-docker
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  annotation-tool:
    build:
      context: ./annotation-tool 
      dockerfile: Dockerfile      
    ports:
      - "127.0.0.1:8081:3000"   
    environment:
      - HOST=0.0.0.0
      - PUBLIC_URL=/annotation-tool         
    command: npm start
    networks:
      - ollama-docker
    depends_on:
      - ollama

  llm-service:
      build:
        context: ./llm-service
        dockerfile: Dockerfile      
      ports:
        - "127.0.0.1:8085:8000"   
      environment:
        - HOST=0.0.0.0         
        - OLLAMA_HOST=ollama
        - EMBEDDING_MODELS=bge-m3
        - LLM_MODELS=llama3.1:8b-instruct-fp16,mixtral:8x7b-instruct-v0.1-q2_K
        - ALLOWED_ORIGINS=http://rag.ki.rtr.at,https://rag.ki.rtr.at
        - TEMPERATURE=0.1
        - CONTEXT_WINDOW=11500
        - ROOT_PATH=/llm-service
        - TOP_N_CHUNKS=25
      volumes:
        - ./data/combined.json:/app/data/chunks.json
      networks:
        - ollama-docker
      depends_on:
        - ollama

  user-interface:
    build:
      context: ./user-interface
      dockerfile: Dockerfile      
    ports:
      - "127.0.0.1:8090:80"   
    environment:
      - HOST=0.0.0.0 
      - LLM_ENDPOINT=https://rag.ki.rtr.at/llm-service  #Known issue, currently doesn't replace the actual environment variable in Angular          
    networks:
      - ollama-docker
    depends_on:
      - llm-service

networks:
  ollama-docker:
    external: false
