services:
  ollama:
    volumes:
      - /app/ollama/data:/root/.ollama
    container_name: ollama
    pull_policy: always
    tty: true
    restart: unless-stopped
    image: ollama/ollama:latest
    ports:
      - 127.0.0.1:11434:11434
    environment:
      - OLLAMA_KEEP_ALIVE=1h
      - OLLAMA_NUM_PARALLEL=1
    networks:
      - ollama-docker
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  annotation-tool:
    build:
      context: ./annotation-tool 
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "127.0.0.1:8081:3000"
    environment:
      - HOST=0.0.0.0
      - PUBLIC_URL=/annotation-tool
    command: npm start
    networks:
      - ollama-docker
    depends_on:
      - ollama

  llm-service:
      privileged: true
      build:
        context: ./llm-service
        dockerfile: Dockerfile
      restart: unless-stopped
      ports:
        - "127.0.0.1:8085:8000"
      env_file:
      - path: matomo.env
        required: false
      environment:
        - HOST=0.0.0.0
        - OLLAMA_HOST=ollama
        - EMBEDDING_MODELS=snowflake-arctic-embed2
        - LLM_MODELS=phi4,llama3.1:8b-instruct-fp16,mixtral:8x7b-instruct-v0.1-q2_K
        - ALLOWED_ORIGINS=http://rag.ki.rtr.at,https://rag.ki.rtr.at
        - TEMPERATURE=0.1
        - CONTEXT_WINDOW=11500
        - ROOT_PATH=/llm-service
        - TOP_N_CHUNKS=25
        - MATOMO_ENDPOINT=${MATOMO_ENDPOINT}
        - MATOMO_TOKEN=${MATOMO_TOKEN}
        - MATOMO_SITE_ID=${MATOMO_SITE_ID}
        - ORDER_CHUNKS_FROM_SOURCE=true
      volumes:
        - ./data/combined.json:/app/data/chunks.json
        - /sys/class/powercap:/sys/class/powercap:ro
        - /proc/stat:/proc/stat:ro
        - /proc/cpuinfo:/proc/cpuinfo:ro
        - /sys/devices/system/cpu:/sys/devices/system/cpu:ro
      devices:
        - /dev/nvidia0:/dev/nvidia0
        - /dev/nvidiactl:/dev/nvidiactl
        - /dev/nvidia-modeset:/dev/nvidia-modeset
        - /dev/nvidia-uvm:/dev/nvidia-uvm
      networks:
        - ollama-docker
      depends_on:
        - ollama
      deploy:
        resources:
          reservations:
            devices:
              - driver: nvidia
                count: 1
                capabilities: [gpu]


  user-interface:
    build:
      context: ./user-interface
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "127.0.0.1:8090:80"   
    environment:
      - HOST=0.0.0.0 
      - LLM_ENDPOINT=https://rag.ki.rtr.at/llm-service  #Known issue, currently doesn't replace the actual environment variable in Angular
    networks:
      - ollama-docker
    depends_on:
      - llm-service

networks:
  ollama-docker:
    external: false
