# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: User Interface CI

on:
  push:
    branches: [ "main" ]
   # paths:
   #   - user-interface/**
  pull_request:
    branches: [ "main" ]
    paths:
      - user-interface/**

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./user-interface
    env:
      CI: ""
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 22
    - run: npm i
    - run: npm run build --if-present --output-path=dist --configuration=production
    - uses: actions/upload-artifact@v4
      with:
        name: build-zip
        path: user-interface/dist/
